server.port=${PORT_RATINGS:8085}
spring.application.name=ratings-service

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# ==========================================
# CASSANDRA / SCYLLA
# ==========================================
spring.cassandra.keyspace-name=${SPRING_CASSANDRA_KEYSPACE_NAME}
spring.cassandra.contact-points=${SPRING_CASSANDRA_CONTACT_POINTS:streaming-scylla}
spring.cassandra.local-datacenter=${SPRING_CASSANDRA_LOCAL_DATACENTER}
spring.cassandra.port=${SPRING_CASSANDRA_PORT}
spring.cassandra.request.timeout=${SPRING_CASSANDRA_REQUEST_TIMEOUT}
spring.cassandra.connection.connect-timeout=${SPRING_CASSANDRA_CONNECT_TIMEOUT}
spring.cassandra.connection.init-query-timeout=${SPRING_CASSANDRA_INIT_QUERY_TIMEOUT}
spring.cassandra.schema-action=${SPRING_CASSANDRA_SCHEMA_ACTION}
# ==========================================
# HTTPS / SERVER SSL
# ==========================================
server.ssl.enabled=${SERVER_SSL_ENABLED}
server.ssl.key-store=${SERVER_SSL_KEY_STORE}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS}

# ==========================================
# TRUST STORE (CLIENT SSL)
# ==========================================
server.ssl.trust-store=${SERVER_SSL_TRUST_STORE}
server.ssl.trust-store-password=${SERVER_SSL_TRUST_STORE_PASSWORD}
server.ssl.trust-store-type=${SERVER_SSL_TRUST_STORE_TYPE}

# ==========================================
# 3. EUREKA CONFIG (Register as Secure)
# ==========================================
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.hostname=${spring.application.name}

# Explicitly tell Eureka Clients to talk to me via HTTPS
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/actuator/health