server.port=${PORT_NOTIFICATIONS:8084}
spring.application.name=notification-service

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#moje
spring.cassandra.keyspace-name=notifications_ks
spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINTS:scylla}
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.port=9042

spring.cassandra.schema-action=CREATE_IF_NOT_EXISTS