apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
  namespace: hear-we-go
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode-pvc
  namespace: hear-we-go
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-namenode
  namespace: hear-we-go
spec:
  selector: { matchLabels: { app: streaming-namenode } }
  template:
    metadata: { labels: { app: streaming-namenode } }
    spec:
      containers:
        - name: streaming-namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          env:
            - name: CLUSTER_NAME
              value: "test"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
          ports:
            - containerPort: 9870
            - containerPort: 8020
          volumeMounts:
            - name: namenode-data
              mountPath: /hadoop/dfs/name
      volumes:
        - name: namenode-data
          persistentVolumeClaim: { claimName: namenode-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-namenode
  namespace: hear-we-go
spec:
  selector: { app: streaming-namenode }
  ports:
    - name: web
      port: 9870
      targetPort: 9870
    - name: hdfs
      port: 8020
      targetPort: 8020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-datanode
  namespace: hear-we-go
spec:
  selector: { matchLabels: { app: streaming-datanode } }
  template:
    metadata: { labels: { app: streaming-datanode } }
    spec:
      containers:
        - name: streaming-datanode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          env:
            - name: SERVICE_PRECONDITION
              value: "streaming-namenode:9870"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://streaming-namenode:8020"
          volumeMounts:
            - name: datanode-data
              mountPath: /hadoop/dfs/data
      volumes:
        - name: datanode-data
          persistentVolumeClaim: { claimName: datanode-pvc }