apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-kafka
  namespace: hear-we-go
spec:
  selector:
    matchLabels:
      app: streaming-kafka
  template:
    metadata:
      labels:
        app: streaming-kafka
    spec:
      containers:
        - name: streaming-kafka
          image: redpandadata/redpanda:latest
          # We use 'args' instead of 'command' for cleaner syntax
          args:
            - redpanda
            - start
            - --mode=dev-container
            - --smp=1
            - --memory=512M
            - --kafka-addr
            - internal://0.0.0.0:9092,external://0.0.0.0:29092
            - --advertise-kafka-addr
            - internal://streaming-kafka:9092,external://localhost:29092
          ports:
            - containerPort: 9092
            - containerPort: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-kafka
  namespace: hear-we-go
spec:
  selector:
    app: streaming-kafka
  ports:
    - port: 9092
      name: internal
      targetPort: 9092
    - port: 29092
      name: external
      targetPort: 29092