apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: hear-we-go
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          args: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: hear-we-go
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: loki
#  namespace: hear-we-go
#spec:
#  replicas: 1 # Ensure this is 1!
#  selector:
#    matchLabels:
#      app: loki
#  template:
#    metadata:
#      labels:
#        app: loki
#    spec:
#      containers:
#        - name: nginx-sink
#          image: nginx:alpine
#          command: ["/bin/sh", "-c", "echo 'server { listen 3100; location / { return 204; } }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
#          ports:
#            - containerPort: 3100
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: loki
#  namespace: hear-we-go
#spec:
#  selector:
#    app: loki
#  ports:
#    - port: 3100
#      targetPort: 3100