apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: hear-we-go
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-mongo
  namespace: hear-we-go
spec:
  selector:
    matchLabels:
      app: streaming-mongo
  template:
    metadata:
      labels:
        app: streaming-mongo
    spec:
      containers:
        - name: streaming-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "users-db"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-mongo
  namespace: hear-we-go
spec:
  selector:
    app: streaming-mongo
  ports:
    - port: 27017
      targetPort: 27017