server.port=${PORT_USER:8081}
spring.application.name=users-service

spring.data.mongodb.uri=mongodb://localhost:27017/users-db

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=${JWT_SECRET:some_super_secret_key_or_something_also_default_not_very_secure_something_something}