server.port=${PORT_USER:8081}
spring.application.name=users-service
spring.data.mongodb.uri=mongodb://localhost:27017/users-db
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.secret=${JWT_SECRET:someSuperSecretKeyOrSomethingAlsoDefaultNotVerySecureSomethingSomething}
spring.mail.host=streaming-mailhog
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.properties.mail.debug=true

# ==========================================
# HTTPS / SERVER SSL
# ==========================================
server.ssl.enabled=${SERVER_SSL_ENABLED}
server.ssl.key-store=${SERVER_SSL_KEY_STORE}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS}

# ==========================================
# TRUST STORE (CLIENT SSL)
# ==========================================
server.ssl.trust-store=${SERVER_SSL_TRUST_STORE}
server.ssl.trust-store-password=${SERVER_SSL_TRUST_STORE_PASSWORD}
server.ssl.trust-store-type=${SERVER_SSL_TRUST_STORE_TYPE}

# ==========================================
# 3. EUREKA CONFIG (Register as Secure)
# ==========================================
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.hostname=${spring.application.name}

# Explicitly tell Eureka Clients to talk to me via HTTPS
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/actuator/health


# 2. Set sampling to 100% (1.0) so every request is recorded
management.tracing.sampling.probability=1.0

# 3. Tell Spring where to send the data (Jaeger's OTLP port)
management.otlp.tracing.endpoint=http://host.docker.internal:4318/v1/traces

# 4. Optional: Add Trace IDs to your logs for easier debugging
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# 5. Ensure Actuator endpoints are available
management.endpoints.web.exposure.include=health,info,tracing