server.port=${PORT_CONTENT:8082}
spring.application.name=content-service

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
HDFS_URI=${HDFS_URI:hdfs://namenode:8020}

# ==========================================
# HTTPS / SERVER SSL
# ==========================================
server.ssl.enabled=${SERVER_SSL_ENABLED}
server.ssl.key-store=${SERVER_SSL_KEY_STORE}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS}

# ==========================================
# TRUST STORE (CLIENT SSL)
# ==========================================
server.ssl.trust-store=${SERVER_SSL_TRUST_STORE}
server.ssl.trust-store-password=${SERVER_SSL_TRUST_STORE_PASSWORD}
server.ssl.trust-store-type=${SERVER_SSL_TRUST_STORE_TYPE}

# ==========================================
# 3. EUREKA CONFIG (Register as Secure)
# ==========================================
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.hostname=${spring.application.name}

# Explicitly tell Eureka Clients to talk to me via HTTPS
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/actuator/health

# Key is a String (e.g. topic name)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value is a JSON Object (ContentCreatedEvent) -- THIS IS THE FIX
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.type.mapping=\
#  contentCreated:com.streaming.common.event.ContentCreatedEvent,\
#  songDeleted:com.streaming.common.event.SongDeletedEvent