server.port=${PORT_EUREKA:8761}
spring.application.name=discovery-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

# ==========================================
# HTTPS / SERVER SSL
# ==========================================
server.ssl.enabled=${SERVER_SSL_ENABLED}
server.ssl.key-store=${SERVER_SSL_KEY_STORE}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE}
server.ssl.key-alias=${SERVER_SSL_KEY_ALIAS}

# ==========================================
# TRUST STORE (CLIENT SSL)
# ==========================================
server.ssl.trust-store=${SERVER_SSL_TRUST_STORE}
server.ssl.trust-store-password=${SERVER_SSL_TRUST_STORE_PASSWORD}
server.ssl.trust-store-type=${SERVER_SSL_TRUST_STORE_TYPE}

# ==========================================
# 3. EUREKA CONFIG (Register as Secure)
# ==========================================
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.hostname=${spring.application.name}

# Explicitly tell Eureka Clients to talk to me via HTTPS
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/actuator/health

eureka.client.service-url.defaultZone=https://localhost:8761/eureka/