db1 = db.getSiblingDB("users-db");
db2 = db.getSiblingDB("content-db");

db1.users.insertMany([
    {
        username: "aleksa",
        email: "velickovicaleksa555@gmail.com",
        firstName: "Aleksa",
        lastName: "Velickovic",
        passwordHash: "$2y$10$OFPT0FcURNXGpHnVNKSu2Ox.7kkT1Ii0JjjBc/RVsiB17pLlfI2JK",
        role: "USER",
        active: true,
        lastPasswordReset: new Date("2025-01-01T12:00:00Z"),
        registrationStatus: "APPROVED"
    },
    {
        username: "testuser",
        email: "a.velickovic333@gmail.com",
        firstName: "Test",
        lastName: "User",
        passwordHash: "$2y$10$L2ZvWUzS1iifI8Gh9NxDnuZU09GeClN9IfII68S/U/UrYQLHORiwm",
        role: "USER",
        active: true,
        lastPasswordReset: new Date("2025-02-01T09:30:00Z"),
        registrationStatus: "APPROVED"
    },
    {
        // id: "adminuser",
        username: "admin",
        email: "aleksavelickovic555@gmail.com",
        firstName: "Admin",
        lastName: "Korisnik",
        passwordHash: "$2a$08$XpEZA8ehk7xf0FHQqVEpze3cnwMwhIVPGxqtTM7BVN.pNxIy2Yd9W",
        role: "ADMIN",
        active: true,
        lastPasswordReset: new Date("2026-01-01T09:30:00Z"),
        registrationStatus: "APPROVED"
    },
    {
        username: "adminold",
        email: "akica208@gmail.com",
        firstName: "Admin",
        lastName: "Korisnik",
        passwordHash: "$2y$10$FNSNzwxBvqfSlPgSdUbZvOmrUUtaXd0j7nOyfeMZElAWDfm/3ZxIy",
        role: "ADMIN",
        active: true,
        lastPasswordReset: new Date("2021-02-01T09:30:00Z"),
        registrationStatus: "APPROVED"
    },
    {
        username: "milan",
        email: "maricmilan0414@gmail.com",
        firstName: "Admin",
        lastName: "Korisnik",
        passwordHash: "$2y$10$FNSNzwxBvqfSlPgSdUbZvOmrUUtaXd0j7nOyfeMZElAWDfm/3ZxIy",
        role: "ADMIN",
        active: true,
        lastPasswordReset: new Date("2025-02-01T09:30:00Z"),
        registrationStatus: "APPROVED"
    }
]);

const artist1Id = "artist-101";
const artist2Id = "artist-102";

db2.artists.insertMany([
    {
        "_id": artist1Id,
        "name": "The Java Architects",
        "biography": "A band formed inside a Docker container. Known for their strict object-oriented melodies.",
        "genres": ["Rock", "Indie"],
        "imageUrl": "https://placehold.co/400",
        "_class": "com.streaming.content.model.Artist"
    },
    {
        "_id": artist2Id,
        "name": "Synthwave Systems",
        "biography": "Electronic beats generated by AI.",
        "genres": ["Electronic", "Synthwave"],
        "imageUrl": "https://placehold.co/400",
        "_class": "com.streaming.content.model.Artist"
    }
]);

const album1Id = "album-201";
const album2Id = "album-202";

db2.albums.insertMany([
    {
        "_id": album1Id,
        "title": "Spring Boot Breakdown",
        "releaseDate": new Date("2024-01-15T00:00:00Z"),
        "genre": "Rock",
        "artistIds": [artist1Id],
        "_class": "com.streaming.content.model.Album"
    },
    {
        "_id": album2Id,
        "title": "Neon Future",
        "releaseDate": new Date("2025-05-20T00:00:00Z"),
        "genre": "Synthwave",
        "artistIds": [artist2Id],
        "_class": "com.streaming.content.model.Album"
    }
]);

db2.songs.insertMany([
    {
        "_id": "song-01",
        "title": "Dependency Injection Blues",
        "durationSeconds": 42,
        "genre": "Rock",
        "albumId": album1Id,
        "artistIds": [artist1Id],
        "audioFilePath": "hdfs://namenode:8020/music/sample-42s.mp3",
        "checksum": "e99a18c428cb38d5f260853678922e03",
        "_class": "com.streaming.content.model.Song"
    },
    {
        "_id": "song-02",
        "title": "Null Pointer Ballad",
        "durationSeconds": 42,
        "genre": "Indie",
        "albumId": album1Id,
        "artistIds": [artist1Id],
        "audioFilePath": "hdfs://namenode:8020/music/sample-42s.mp3",
        "checksum": "5d41402abc4b2a76b9719d911017c592",
        "_class": "com.streaming.content.model.Song"
    },

    {
        "_id": "song-03",
        "title": "Cyberpunk City",
        "durationSeconds": 42,
        "genre": "Synthwave",
        "albumId": album2Id,
        "artistIds": [artist2Id],
        "audioFilePath": "hdfs://namenode:8020/music/sample-42s.mp3",
        "checksum": "26ab0db90d72e28ad0ba1e22ee510510",
        "_class": "com.streaming.content.model.Song"
    },
    {
        "_id": "song-04",
        "title": "Binary Sunset",
        "durationSeconds": 42,
        "genre": "Electronic",
        "albumId": album2Id,
        "artistIds": [artist2Id],
        "audioFilePath": "hdfs://namenode:8020/music/sample-42s.mp3",
        "checksum": "827ccb0eea8a706c4c34a16891f84e7b",
        "_class": "com.streaming.content.model.Song"
    }
]);
