server.port=${PORT_ANALYTICS:8083}
spring.application.name=analytics-service

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==========================================
# 1. SERVER SSL (I am HTTPS)
# ==========================================
server.ssl.enabled=true
server.ssl.key-store=/app/certs/keystore.p12
server.ssl.key-store-password=password123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

# ==========================================
# 2. CLIENT SSL (I trust other HTTPS services)
# ==========================================
# Since we signed everything with our own CA, we trust our own keystore.
server.ssl.trust-store=/app/certs/keystore.p12
server.ssl.trust-store-password=password123
server.ssl.trust-store-type=PKCS12

# ==========================================
# 3. EUREKA CONFIG (Register as Secure)
# ==========================================
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.hostname=${spring.application.name}

# Explicitly tell Eureka Clients to talk to me via HTTPS
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/actuator/health