server.port=${PORT_GATEWAY:8080}
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.discovery.locator.enabled=true

# --- REDIS CONFIGURATION ---
spring.data.redis.host=streaming-redis
spring.data.redis.port=6379

# --- RATE LIMITER CONFIG ---
# replenishRate: How many tokens added per second (Requests per second)
# burstCapacity: Maximum bursts allowed (e.g., user clicks fast 3 times)
spring.cloud.gateway.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.replenishRate=120
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=240
spring.cloud.gateway.routes[1].filters[0].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=120
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=240
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.routes[0].id=users-service
spring.cloud.gateway.routes[0].uri=lb://users-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=content-service
spring.cloud.gateway.routes[1].uri=lb://content-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/content/**

spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=lb://notification-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.routes[3].id=subscriptions-service
spring.cloud.gateway.routes[3].uri=lb://subscriptions-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/subscriptions/**

spring.cloud.gateway.routes[4].id=notification-ws
spring.cloud.gateway.routes[4].uri=${NOTIFICATION_WS_URI}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/ws/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[5].id=recommendation-service
spring.cloud.gateway.routes[5].uri=lb://recommendation-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/recommendations/**

spring.cloud.gateway.routes[6].id=ratings-service
spring.cloud.gateway.routes[6].uri=lb://ratings-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/ratings/**

# 8. ANALYTICS SERVICE
spring.cloud.gateway.routes[7].id=analytics-service
spring.cloud.gateway.routes[7].uri=lb://analytics-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/analytics/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
jwt.secret=${JWT_SECRET:someSuperSecretKeyOrSomethingAlsoDefaultNotVerySecureSomethingSomething}

# ==========================================
# 1. SERVER SSL (I am HTTPS)
# ==========================================
server.ssl.enabled=true
server.ssl.key-store=/app/certs/keystore.p12
server.ssl.key-store-password=password123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

# ==========================================
# 2. CLIENT SSL (I trust other HTTPS services)
# ==========================================
# Since we signed everything with our own CA, we trust our own keystore.
server.ssl.trust-store=/app/certs/keystore.p12
server.ssl.trust-store-password=password123
server.ssl.trust-store-type=PKCS12

# ==========================================
# 3. EUREKA CONFIG (Register as Secure)
# ==========================================
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}
eureka.instance.hostname=${spring.application.name}

# Explicitly tell Eureka Clients to talk to me via HTTPS
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/actuator/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/actuator/health

# ==========================================
# REQ 2.7.6: Explicit Timeout for User Response
# ==========================================
# Time to establish a connection to the backend
spring.cloud.gateway.httpclient.connect-timeout=2000
# Time to wait for a response (The "Deadline")
# If Recommendation Service takes 6 seconds, Gateway kills it at 5s.
spring.cloud.gateway.httpclient.response-timeout=5000

# 2. Set sampling to 100% (1.0) so every request is recorded
management.tracing.sampling.probability=1.0

# 3. Tell Spring where to send the data (Jaeger's OTLP port)
management.otlp.tracing.endpoint=http://host.docker.internal:4318/v1/traces

# 4. Optional: Add Trace IDs to your logs for easier debugging
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# 5. Ensure Actuator endpoints are available
management.endpoints.web.exposure.include=health,info,tracing