server.port=${PORT_GATEWAY:8080}
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.discovery.locator.enabled=false

# WebSocket CORS konfiguracija
spring.cloud.gateway.default-filters=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
## 0. WEB SOCKET RUTA
#spring.cloud.gateway.routes[0].id=notification-websocket
#spring.cloud.gateway.routes[0].uri=http://notification-service:8084
#spring.cloud.gateway.routes[0].predicates[0]=Path=/ws/**

# 1. USERS SERVICE
spring.cloud.gateway.routes[1].id=users-service
spring.cloud.gateway.routes[1].uri=lb://users-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# 2. CONTENT SERVICE
spring.cloud.gateway.routes[2].id=content-service
spring.cloud.gateway.routes[2].uri=lb://content-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/content/**

# 3. NOTIFICATION SERVICE (API deo)
spring.cloud.gateway.routes[3].id=notification-service
spring.cloud.gateway.routes[3].uri=lb://notification-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/notifications/**

# 4. SUBSCRIPTIONS SERVICE
spring.cloud.gateway.routes[4].id=subscriptions-service
spring.cloud.gateway.routes[4].uri=lb://subscriptions-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/subscriptions/**

# ---------------------------------------------------------
# GLOBALNI CORS (Prilago?en za SockJS i WebSockete)
# ---------------------------------------------------------
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=http://localhost:4200,http://localhost,http://localhost:*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

jwt.secret=${JWT_SECRET:someSuperSecretKeyOrSomethingAlsoDefaultNotVerySecureSomethingSomething}

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.client=DEBUG