apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-service
  namespace: hear-we-go
spec:
  replicas: 1
  selector: { matchLabels: { app: ratings-service } }
  template:
    metadata: { labels: { app: ratings-service } }
    spec:
      containers:
        - name: ratings-service
          image: hear-we-go-ratings-service:latest # CHECK THIS NAME
          imagePullPolicy: Never
          envFrom:
            - configMapRef: { name: app-config }
          env:
#            - name: SERVER_PORT
#              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://streaming-jaeger:4318"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "streaming-kafka:9092"
            - name: SPRING_CASSANDRA_CONTACT_POINTS
              value: "streaming-scylla"
            - name: SPRING_CASSANDRA_PORT
              value: "9042"
            - name: SPRING_CASSANDRA_KEYSPACE_NAME
              value: "ratings_ks"        # <--- Different value here!
            - name: SPRING_CASSANDRA_LOCAL_DATACENTER
              value: "datacenter1"
#          ports:
#            - containerPort: 8080
          volumeMounts:
            - name: certs-volume
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: certs-volume
          secret: { secretName: cert-secret }
---
apiVersion: v1
kind: Service
metadata:
  name: ratings-service
  namespace: hear-we-go
spec:
  selector: { app: ratings-service }
  type: ClusterIP # Exposes Gateway externally just in case
  ports:
    - name: "https"
      port: 8085
      targetPort: 8085
#    - name: "http"
#      port: 8085
#      targetPort: 8085